/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package papers;

/**
 *
 * @author User
 */
public class Subject extends javax.swing.JInternalFrame {

    /**
     * Creates new form Subject
     */
    public Subject() {
        initComponents();
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pictureBox1 = new papers.PictureBox();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        pictureBox2 = new papers.PictureBox();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        pictureBox4 = new papers.PictureBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        pictureBox5 = new papers.PictureBox();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        pictureBox6 = new papers.PictureBox();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pictureBox11 = new papers.PictureBox();
        pictureBox3 = new papers.PictureBox();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        pictureBox9 = new papers.PictureBox();
        pictureBox10 = new papers.PictureBox();
        jLabel9 = new javax.swing.JLabel();
        pictureBox7 = new papers.PictureBox();
        jLabel2 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        pictureBox12 = new papers.PictureBox();
        pictureBox8 = new papers.PictureBox();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        pictureBox13 = new papers.PictureBox();
        jPanel2 = new javax.swing.JPanel();
        pictureBox14 = new papers.PictureBox();
        pictureBox15 = new papers.PictureBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pictureBox1.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/WhatsApp Image 2024-10-23 at 15.20.23.jpeg"))); // NOI18N
        jPanel1.add(pictureBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 210));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Subjects" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Your Current Subject");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1600, 220, 190, 30));

        pictureBox2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));
        pictureBox2.add(jSeparator1);
        jSeparator1.setBounds(70, 30, 120, 10);

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PAPERS NUMBER");
        pictureBox2.add(jLabel4);
        jLabel4.setBounds(70, 10, 120, 16);

        pictureBox4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        pictureBox4.add(jSeparator3);
        jSeparator3.setBounds(80, 30, 60, 10);

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Papers Number");
        pictureBox4.add(jLabel5);
        jLabel5.setBounds(70, 10, 120, 18);

        pictureBox2.add(pictureBox4);
        pictureBox4.setBounds(0, 0, 0, 0);

        pictureBox5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        pictureBox5.add(jSeparator4);
        jSeparator4.setBounds(80, 30, 60, 10);

        jLabel6.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Papers Number");
        pictureBox5.add(jLabel6);
        jLabel6.setBounds(70, 10, 120, 18);

        pictureBox6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 102, 0), 1, true));
        pictureBox6.add(jSeparator5);
        jSeparator5.setBounds(80, 30, 60, 10);

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Papers Number");
        pictureBox6.add(jLabel7);
        jLabel7.setBounds(70, 10, 120, 18);

        pictureBox5.add(pictureBox6);
        pictureBox6.setBounds(0, 0, 0, 0);

        pictureBox2.add(pictureBox5);
        pictureBox5.setBounds(0, 0, 0, 0);

        jLabel10.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("1020");
        pictureBox2.add(jLabel10);
        jLabel10.setBounds(100, 70, 70, 30);

        pictureBox11.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-papers-100.png"))); // NOI18N
        pictureBox2.add(pictureBox11);
        pictureBox11.setBounds(100, 120, 70, 60);

        jPanel1.add(pictureBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 280, 230));

        pictureBox3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("SCORES");
        pictureBox3.add(jLabel3);
        jLabel3.setBounds(90, 10, 100, 30);

        jSeparator2.setBackground(new java.awt.Color(204, 204, 204));
        pictureBox3.add(jSeparator2);
        jSeparator2.setBounds(90, 38, 60, 2);
        pictureBox3.add(pictureBox9);
        pictureBox9.setBounds(10, 80, 0, 0);

        pictureBox10.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-score-50.png"))); // NOI18N
        pictureBox3.add(pictureBox10);
        pictureBox10.setBounds(100, 120, 60, 60);

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("215325.00");
        pictureBox3.add(jLabel9);
        jLabel9.setBounds(70, 70, 130, 30);

        jPanel1.add(pictureBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 280, 230));

        pictureBox7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0)));

        jLabel2.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YOUR RANK");
        pictureBox7.add(jLabel2);
        jLabel2.setBounds(100, 10, 100, 20);
        pictureBox7.add(jSeparator6);
        jSeparator6.setBounds(100, 32, 90, 10);

        jLabel11.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("120");
        pictureBox7.add(jLabel11);
        jLabel11.setBounds(110, 70, 60, 28);

        pictureBox12.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-rank-100.png"))); // NOI18N
        pictureBox7.add(pictureBox12);
        pictureBox12.setBounds(110, 120, 70, 60);

        jPanel1.add(pictureBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 270, 280, 230));

        pictureBox8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 1, true));

        jLabel8.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AVG");
        pictureBox8.add(jLabel8);
        jLabel8.setBounds(110, 10, 29, 20);
        pictureBox8.add(jSeparator7);
        jSeparator7.setBounds(100, 30, 50, 2);

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("9.2 %");
        pictureBox8.add(jLabel12);
        jLabel12.setBounds(100, 70, 70, 20);

        pictureBox13.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-average-100.png"))); // NOI18N
        pictureBox8.add(pictureBox13);
        pictureBox13.setBounds(90, 110, 90, 70);

        jPanel1.add(pictureBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1350, 270, 280, 230));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        pictureBox14.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/Quizzy_Bee__2_-removebg-preview.png"))); // NOI18N

        pictureBox15.setImage(new javax.swing.ImageIcon(getClass().getResource("/images/leadlogoblack.png"))); // NOI18N

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("powered by ");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("@QuzzyBee");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(pictureBox14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(329, 329, 329)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(pictureBox15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1081, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pictureBox14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pictureBox15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 900, 1920, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"#1", "Mathematics", null},
                {"#2", "Science", null},
                {"#3", "Sinhala", null},
                {"#4", "Civic", null},
                {"#5", "Health", null},
                {"#6", "Geography", null},
                {"#7", "ICT", null},
                {"#8", "English", null},
                {"#9", "Music", null}
            },
            new String [] {
                "Subject id", "Subject name", "Status"
            }
        ));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 580, 1140, 180));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private papers.PictureBox pictureBox1;
    private papers.PictureBox pictureBox10;
    private papers.PictureBox pictureBox11;
    private papers.PictureBox pictureBox12;
    private papers.PictureBox pictureBox13;
    private papers.PictureBox pictureBox14;
    private papers.PictureBox pictureBox15;
    private papers.PictureBox pictureBox2;
    private papers.PictureBox pictureBox3;
    private papers.PictureBox pictureBox4;
    private papers.PictureBox pictureBox5;
    private papers.PictureBox pictureBox6;
    private papers.PictureBox pictureBox7;
    private papers.PictureBox pictureBox8;
    private papers.PictureBox pictureBox9;
    // End of variables declaration//GEN-END:variables
}
